/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/draft/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft Analysis */
        get: operations["draft_analysis_api_draft_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_feedback_get"];
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keepers/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keeper Board */
        get: operations["keeper_board_api_keepers_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managers */
        get: operations["list_managers_api_managers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers/{manager_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manager */
        get: operations["get_manager_api_managers__manager_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers/{manager_id}/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manager Streak */
        get: operations["get_manager_streak_api_managers__manager_id__streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season */
        get: operations["get_season_api_seasons__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Matchups */
        get: operations["get_season_matchups_api_seasons__year__matchups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/alltime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Time Stats */
        get: operations["all_time_stats_api_stats_alltime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Awards */
        get: operations["awards_api_stats_awards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consistency */
        get: operations["consistency_api_stats_consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/consolation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consolation Bracket */
        get: operations["consolation_bracket_api_stats_consolation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/droughts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Droughts */
        get: operations["droughts_api_stats_droughts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/headtohead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head To Head */
        get: operations["head_to_head_api_stats_headtohead_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/insight-rankings/{insight_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insight Rankings */
        get: operations["insight_rankings_api_stats_insight_rankings__insight_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/league-parity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** League Parity */
        get: operations["league_parity_api_stats_league_parity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/luck-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Luck Index */
        get: operations["luck_index_api_stats_luck_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/manager-placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manager Placements */
        get: operations["manager_placements_api_stats_manager_placements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/manager-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manager Tiers */
        get: operations["manager_tiers_api_stats_manager_tiers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/playoff-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playoff Performance */
        get: operations["playoff_performance_api_stats_playoff_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/points-inflation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Points Inflation */
        get: operations["points_inflation_api_stats_points_inflation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/power-rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Power Rankings */
        get: operations["power_rankings_api_stats_power_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/projection-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projection Performance */
        get: operations["projection_performance_api_stats_projection_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/rivalry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rivalry */
        get: operations["rivalry_api_stats_rivalry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/score-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Score Distribution */
        get: operations["score_distribution_api_stats_score_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/season-scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Scoring */
        get: operations["season_scoring_api_stats_season_scoring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/streaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streaks */
        get: operations["streaks_api_stats_streaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/strength-of-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strength Of Schedule */
        get: operations["strength_of_schedule_api_stats_strength_of_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/throne-tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Throne Tracker */
        get: operations["throne_tracker_api_stats_throne_tracker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/trophy-case/{manager_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trophy Case */
        get: operations["trophy_case_api_stats_trophy_case__manager_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/weekly-finish-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Finish Distribution */
        get: operations["weekly_finish_distribution_api_stats_weekly_finish_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/weekly-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Records */
        get: operations["weekly_records_api_stats_weekly_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/win-margins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Win Margins */
        get: operations["win_margins_api_stats_win_margins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Log */
        get: operations["sync_log_api_sync_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Award */
        Award: {
            /** Award Name */
            award_name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Value */
            value: string;
        };
        /** BestWorstPick */
        BestWorstPick: {
            /** Fantasy Points */
            fantasy_points: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Pick */
            pick: number;
            /** Pick Value */
            pick_value: number;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string;
            /** Roi */
            roi: number;
            /** Round */
            round: number;
            /** Year */
            year: number;
        };
        /** ConsistencyRow */
        ConsistencyRow: {
            /** Avg Score */
            avg_score: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Max Score */
            max_score: number;
            /** Min Score */
            min_score: number;
            /** Std Dev */
            std_dev: number;
            /** Year */
            year: number | null;
        };
        /** ConsolationRow */
        ConsolationRow: {
            /** Consolation Avg Points */
            consolation_avg_points: number;
            /** Consolation Games */
            consolation_games: number;
            /** Consolation Losses */
            consolation_losses: number;
            /** Consolation Win Pct */
            consolation_win_pct: number;
            /** Consolation Wins */
            consolation_wins: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Times Missed Playoffs */
            times_missed_playoffs: number;
        };
        /** DraftAnalysis */
        DraftAnalysis: {
            /** Best Picks */
            best_picks: components["schemas"]["BestWorstPick"][];
            /** Grades */
            grades: components["schemas"]["DraftGradeRow"][];
            /** Position Capital */
            position_capital: components["schemas"]["PositionCapitalRow"][];
            /** Tendencies */
            tendencies: components["schemas"]["DraftTendencyRow"][];
            /** Worst Picks */
            worst_picks: components["schemas"]["BestWorstPick"][];
        };
        /** DraftGradeRow */
        DraftGradeRow: {
            /** Avg Roi */
            avg_roi: number;
            /** Composite Score */
            composite_score: number;
            /** Grade */
            grade: string;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Total Picks */
            total_picks: number;
            /** Year */
            year: number;
        };
        /** DraftTendencyRow */
        DraftTendencyRow: {
            /** Early Round Pct */
            early_round_pct: number;
            /** Late Round Pct */
            late_round_pct: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Mid Round Pct */
            mid_round_pct: number;
            /** Position */
            position: string;
        };
        /** DroughtRow */
        DroughtRow: {
            /** Last Championship Year */
            last_championship_year: number | null;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Seasons Since */
            seasons_since: number;
            /** Total Championships */
            total_championships: number;
        };
        /** Dynasty */
        Dynasty: {
            /** Count */
            count: number;
            /** Manager Name */
            manager_name: string;
            /** Years */
            years: number[];
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            /** Author Name */
            author_name: string;
            /** Message */
            message: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Author Name */
            author_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Message */
            message: string;
        };
        /** H2HManager */
        H2HManager: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** H2HMatrix */
        H2HMatrix: {
            /** Managers */
            managers: components["schemas"]["H2HManager"][];
            /** Records */
            records: components["schemas"]["H2HRecord"][];
        };
        /** H2HRecord */
        H2HRecord: {
            /** Losses */
            losses: number;
            /** Manager A Id */
            manager_a_id: number;
            /** Manager A Name */
            manager_a_name: string;
            /** Manager B Id */
            manager_b_id: number;
            /** Manager B Name */
            manager_b_name: string;
            /** Points Against */
            points_against: number;
            /** Points For */
            points_for: number;
            /** Ties */
            ties: number;
            /** Win Pct */
            win_pct: number;
            /** Wins */
            wins: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** InflationPoint */
        InflationPoint: {
            /** Avg Weekly Score */
            avg_weekly_score: number;
            /** Max Weekly Score */
            max_weekly_score: number;
            /** Min Weekly Score */
            min_weekly_score: number;
            /** Year */
            year: number;
        };
        /** InsightRankingEntry */
        InsightRankingEntry: {
            /** Display Value */
            display_value: string;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Rank */
            rank: number;
            /** Value */
            value: number;
        };
        /** InsightRankingGroup */
        InsightRankingGroup: {
            /** Description */
            description: string;
            /** Entries */
            entries: components["schemas"]["InsightRankingEntry"][];
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Metric Key */
            metric_key: string;
            /** Title */
            title: string;
        };
        /** InsightRankings */
        InsightRankings: {
            /** Groups */
            groups: components["schemas"]["InsightRankingGroup"][];
            /** Insight Key */
            insight_key: string;
        };
        /** KeeperAdpPlayer */
        KeeperAdpPlayer: {
            /** Adp Round */
            adp_round: number;
            /** Average Adp */
            average_adp: number | null;
            /** Nfl Team */
            nfl_team: string | null;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Rank */
            rank: number;
        };
        /** KeeperAdpSnapshot */
        KeeperAdpSnapshot: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Id */
            id: number;
            /** Is Locked */
            is_locked: boolean;
            /** Player Count */
            player_count: number;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string | null;
        };
        /** KeeperBoard */
        KeeperBoard: {
            /** Adp Players */
            adp_players: components["schemas"]["KeeperAdpPlayer"][];
            adp_snapshot: components["schemas"]["KeeperAdpSnapshot"] | null;
            /** Candidates */
            candidates: components["schemas"]["KeeperCandidate"][];
            /** Data Warnings */
            data_warnings: string[];
            rules: components["schemas"]["KeeperRules"];
            /** Teams */
            teams: components["schemas"]["KeeperTeam"][];
        };
        /** KeeperCandidate */
        KeeperCandidate: {
            /** Acquisition Label */
            acquisition_label: string;
            /** Adp Rank */
            adp_rank: number | null;
            /** Adp Round */
            adp_round: number | null;
            /** Average Adp */
            average_adp: number | null;
            /** Base Keeper Round */
            base_keeper_round: number | null;
            /** Candidate Id */
            candidate_id: string;
            /** Consecutive Keeper Years */
            consecutive_keeper_years: number | null;
            /** Draft Pick */
            draft_pick: number | null;
            /** Draft Round */
            draft_round: number | null;
            /** Dynasty Locked Round */
            dynasty_locked_round: number | null;
            /** Dynasty Year */
            dynasty_year: number | null;
            /** Eligibility Reason */
            eligibility_reason: string;
            /**
             * Eligibility Status
             * @enum {string}
             */
            eligibility_status: "eligible" | "ineligible" | "review";
            /** History Known */
            history_known: boolean;
            /** Is Dynasty */
            is_dynasty: boolean | null;
            /** Kept Previous Year */
            kept_previous_year: boolean | null;
            /** Manager Name */
            manager_name: string;
            /** Nfl Team */
            nfl_team: string | null;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string;
            /** Roster Team Key */
            roster_team_key: string;
            /** Roster Team Name */
            roster_team_name: string | null;
            /** Value Rating */
            value_rating: string;
            /** Value Rounds */
            value_rounds: number | null;
            /** Yahoo Player Id */
            yahoo_player_id: string | null;
        };
        /** KeeperRules */
        KeeperRules: {
            /** Adp Source */
            adp_source: string;
            /** Adp Url */
            adp_url: string;
            /** Draft Rounds */
            draft_rounds: number;
            /** League Size */
            league_size: number;
            /** Recap */
            recap: string[];
            /** Scoring Format */
            scoring_format: string;
            /** Season */
            season: number;
            /** Source Season */
            source_season: number;
        };
        /** KeeperTeam */
        KeeperTeam: {
            /** Is Expansion */
            is_expansion: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Round Capacities */
            round_capacities: {
                [key: string]: number;
            };
            /** Team Name */
            team_name: string | null;
        };
        /** LeagueParityRow */
        LeagueParityRow: {
            /** Avg Points Per Game */
            avg_points_per_game: number;
            /** Closest Standings Gap */
            closest_standings_gap: number;
            /** Gini Coefficient */
            gini_coefficient: number;
            /** Num Teams */
            num_teams: number;
            /** Record Spread */
            record_spread: number;
            /** Scoring Range */
            scoring_range: number;
            /** Scoring Std Dev */
            scoring_std_dev: number;
            /** Year */
            year: number;
        };
        /** LuckIndexRow */
        LuckIndexRow: {
            /** Actual Wins */
            actual_wins: number;
            /** Expected Wins */
            expected_wins: number;
            /** Luck Score */
            luck_score: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Year */
            year: number | null;
        };
        /** ManagerBadge */
        ManagerBadge: {
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** ManagerOpponentIdentity */
        ManagerOpponentIdentity: {
            /** Games */
            games: number;
            /** Losses */
            losses: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Point Diff */
            point_diff: number;
            /** Points Against */
            points_against: number;
            /** Points For */
            points_for: number;
            /** Ties */
            ties: number;
            /** Win Pct */
            win_pct: number;
            /** Wins */
            wins: number;
        };
        /** ManagerOut */
        ManagerOut: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
            /** Nickname */
            nickname: string | null;
            /** Yahoo Guid */
            yahoo_guid: string;
        };
        /** ManagerPlacementRow */
        ManagerPlacementRow: {
            /** Average Finish */
            average_finish: number;
            /** Best Finish */
            best_finish: number;
            /** Championships */
            championships: number;
            /** Finish Percentile */
            finish_percentile: number | null;
            /** Last Place Finishes */
            last_place_finishes: number;
            /** Last Place Rate */
            last_place_rate: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Median Finish */
            median_finish: number;
            /** Placement Rank */
            placement_rank: number;
            /** Playoff Appearances */
            playoff_appearances: number;
            /** Playoff Rate */
            playoff_rate: number;
            /** Ranked Seasons */
            ranked_seasons: number;
            /** Runner Ups */
            runner_ups: number;
            /** Seasons Played */
            seasons_played: number;
            /** Top Three Finishes */
            top_three_finishes: number;
            /** Top Three Rate */
            top_three_rate: number;
            /** Worst Finish */
            worst_finish: number;
        };
        /** ManagerPlacementSummary */
        ManagerPlacementSummary: {
            /** Average Finish */
            average_finish: number;
            /** Best Finish */
            best_finish: number;
            /** Championships */
            championships: number;
            /** Finish Percentile */
            finish_percentile: number | null;
            /** Last Place Finishes */
            last_place_finishes: number;
            /** Last Place Rate */
            last_place_rate: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Median Finish */
            median_finish: number;
            /** Placement Rank */
            placement_rank: number;
            /** Playoff Appearances */
            playoff_appearances: number;
            /** Playoff Rate */
            playoff_rate: number;
            /** Ranked Seasons */
            ranked_seasons: number;
            /** Runner Ups */
            runner_ups: number;
            /** Seasons Played */
            seasons_played: number;
            /** Top Three Finishes */
            top_three_finishes: number;
            /** Top Three Rate */
            top_three_rate: number;
            /** Worst Finish */
            worst_finish: number;
        };
        /** ManagerProfile */
        ManagerProfile: {
            manager: components["schemas"]["ManagerOut"];
            /** Season History */
            season_history: components["schemas"]["ManagerSeasonRow"][];
            summary: components["schemas"]["ManagerProfileSummary"] | null;
        };
        /** ManagerProfileSummary */
        ManagerProfileSummary: {
            /** Badges */
            badges: components["schemas"]["ManagerBadge"][];
            closest_rivalry: components["schemas"]["ManagerOpponentIdentity"] | null;
            favorite_opponent: components["schemas"]["ManagerOpponentIdentity"] | null;
            nemesis: components["schemas"]["ManagerOpponentIdentity"] | null;
            placement: components["schemas"]["ManagerPlacementSummary"];
            signature_season: components["schemas"]["ManagerSignatureSeason"] | null;
        };
        /** ManagerSeasonRow */
        ManagerSeasonRow: {
            /** Final Rank */
            final_rank: number | null;
            /** Finish Percentile */
            finish_percentile: number | null;
            /** Is Champion */
            is_champion: boolean;
            /** Losses */
            losses: number;
            /** Made Playoffs */
            made_playoffs: boolean;
            /** Num Teams */
            num_teams: number | null;
            /** Playoff Finish */
            playoff_finish: number | null;
            /** Points Against */
            points_against: number;
            /** Points For */
            points_for: number;
            /** Team Name */
            team_name: string | null;
            /** Ties */
            ties: number;
            /** Wins */
            wins: number;
            /** Year */
            year: number;
        };
        /** ManagerSignatureSeason */
        ManagerSignatureSeason: {
            /** Final Finish */
            final_finish: number;
            /** Finish Percentile */
            finish_percentile: number | null;
            /** Is Champion */
            is_champion: boolean;
            /** Losses */
            losses: number;
            /** Points For */
            points_for: number;
            /** Team Name */
            team_name: string | null;
            /** Ties */
            ties: number;
            /** Wins */
            wins: number;
            /** Year */
            year: number;
        };
        /** ManagerStats */
        ManagerStats: {
            /** Average Finish */
            average_finish: number | null;
            /** Best Finish */
            best_finish: number | null;
            /** Championships */
            championships: number;
            /** Current Drought */
            current_drought: number;
            /** Display Name */
            display_name: string;
            /** Finish Percentile */
            finish_percentile: number | null;
            /** Id */
            id: number;
            /** Last Place Finishes */
            last_place_finishes: number;
            /** Median Finish */
            median_finish: number | null;
            /** Nickname */
            nickname: string | null;
            /** Pf Pa Ratio */
            pf_pa_ratio: number;
            /** Playoff Appearances */
            playoff_appearances: number;
            /** Playoff Rate */
            playoff_rate: number;
            /** Runner Ups */
            runner_ups: number;
            /** Seasons Played */
            seasons_played: number;
            /** Top Three Finishes */
            top_three_finishes: number;
            /** Total Losses */
            total_losses: number;
            /** Total Points Against */
            total_points_against: number;
            /** Total Points For */
            total_points_for: number;
            /** Total Ties */
            total_ties: number;
            /** Total Wins */
            total_wins: number;
            /** Win Pct */
            win_pct: number;
            /** Worst Finish */
            worst_finish: number | null;
        };
        /** ManagerStreak */
        ManagerStreak: {
            /** Best Loss Streak */
            best_loss_streak: number;
            /** Best Win Streak */
            best_win_streak: number;
            /** Current Streak Length */
            current_streak_length: number;
            /** Current Streak Type */
            current_streak_type: string;
        };
        /** ManagerTierDimensions */
        ManagerTierDimensions: {
            /** Avg Ppg */
            avg_ppg: number;
            /** Championships */
            championships: number;
            /** Expected Win Pct */
            expected_win_pct: number;
            /** Playoff Rate */
            playoff_rate: number;
            /** Win Pct */
            win_pct: number;
        };
        /** ManagerTierRow */
        ManagerTierRow: {
            /** Avg Ppg */
            avg_ppg: number;
            /** Championships */
            championships: number;
            /** Composite Score */
            composite_score: number;
            /** Consistency Score */
            consistency_score: number;
            dimension_scores: components["schemas"]["ManagerTierDimensions"];
            /** Expected Win Pct */
            expected_win_pct: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Playoff Rate */
            playoff_rate: number;
            /** Seasons Played */
            seasons_played: number;
            /** Tier */
            tier: string;
            /** Win Pct */
            win_pct: number;
        };
        /** MatchupOut */
        MatchupOut: {
            /** Id */
            id: number;
            /** Is Championship */
            is_championship: boolean;
            /** Is Playoff */
            is_playoff: boolean;
            /** League Id */
            league_id: string | null;
            /** Margin */
            margin: number;
            /** Season Year */
            season_year: number;
            /** Team1 Manager Id */
            team1_manager_id: number;
            /** Team1 Manager Name */
            team1_manager_name: string;
            /** Team1 Points */
            team1_points: number;
            /** Team1 Projected */
            team1_projected: number | null;
            /** Team1 Team Name */
            team1_team_name: string | null;
            /** Team1 Yahoo Id */
            team1_yahoo_id: number | null;
            /** Team2 Manager Id */
            team2_manager_id: number;
            /** Team2 Manager Name */
            team2_manager_name: string;
            /** Team2 Points */
            team2_points: number;
            /** Team2 Projected */
            team2_projected: number | null;
            /** Team2 Team Name */
            team2_team_name: string | null;
            /** Team2 Yahoo Id */
            team2_yahoo_id: number | null;
            /** Week */
            week: number;
            /** Winner Manager Id */
            winner_manager_id: number | null;
        };
        /** PlayoffPerformanceRow */
        PlayoffPerformanceRow: {
            /** Delta Avg Pts */
            delta_avg_pts: number;
            /** Delta Win Pct */
            delta_win_pct: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Playoff Avg Pts */
            playoff_avg_pts: number;
            /** Playoff Games */
            playoff_games: number;
            /** Playoff Losses */
            playoff_losses: number;
            /** Playoff Win Pct */
            playoff_win_pct: number;
            /** Playoff Wins */
            playoff_wins: number;
            /** Reg Avg Pts */
            reg_avg_pts: number;
            /** Reg Games */
            reg_games: number;
            /** Reg Losses */
            reg_losses: number;
            /** Reg Win Pct */
            reg_win_pct: number;
            /** Reg Wins */
            reg_wins: number;
        };
        /** PositionCapitalRow */
        PositionCapitalRow: {
            /** Avg Pick */
            avg_pick: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Picks Spent */
            picks_spent: number;
            /** Position */
            position: string;
            /** Total Capital */
            total_capital: number;
        };
        /** PowerDimensions */
        PowerDimensions: {
            /** Consistency */
            consistency: number;
            /** Luck Adjusted */
            luck_adjusted: number;
            /** Playoff Success */
            playoff_success: number;
            /** Scoring */
            scoring: number;
            /** Win Rate */
            win_rate: number;
        };
        /** PowerRankingRow */
        PowerRankingRow: {
            dimensions: components["schemas"]["PowerDimensions"];
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Overall Score */
            overall_score: number;
        };
        /** ProjectionRow */
        ProjectionRow: {
            /** Avg Actual */
            avg_actual: number;
            /** Avg Diff */
            avg_diff: number;
            /** Avg Projected */
            avg_projected: number;
            /** Beat Projection Pct */
            beat_projection_pct: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Std Dev Diff */
            std_dev_diff: number;
            /** Total Over */
            total_over: number;
            /** Weeks */
            weeks: number;
        };
        /** RivalryDetail */
        RivalryDetail: {
            biggest_blowout: components["schemas"]["RivalryMatchup"] | null;
            closest_game: components["schemas"]["RivalryMatchup"] | null;
            current_streak: components["schemas"]["RivalryStreak"];
            longest_streak: components["schemas"]["RivalryStreak"];
            /** Manager A Id */
            manager_a_id: number;
            /** Manager A Name */
            manager_a_name: string;
            /** Manager B Id */
            manager_b_id: number;
            /** Manager B Name */
            manager_b_name: string;
            /** Matchups */
            matchups: components["schemas"]["RivalryMatchup"][];
            summary: components["schemas"]["RivalrySummary"];
            /** Trends */
            trends: components["schemas"]["RivalryTrend"][];
        };
        /** RivalryMatchup */
        RivalryMatchup: {
            /** A Points */
            a_points: number;
            /** B Points */
            b_points: number;
            /** Game Id */
            game_id: number | null;
            /** Is Playoff */
            is_playoff: boolean;
            /** League Id */
            league_id: string | null;
            /** Margin */
            margin: number;
            /** Team A Yahoo Id */
            team_a_yahoo_id: number | null;
            /** Team B Yahoo Id */
            team_b_yahoo_id: number | null;
            /** Week */
            week: number;
            /**
             * Winner
             * @enum {string}
             */
            winner: "a" | "b" | "tie";
            /** Year */
            year: number;
        };
        /** RivalryStreak */
        RivalryStreak: {
            /**
             * Holder
             * @enum {string}
             */
            holder: "a" | "b";
            /** Length */
            length: number;
        };
        /** RivalrySummary */
        RivalrySummary: {
            /** A Pf */
            a_pf: number;
            /** A Wins */
            a_wins: number;
            /** B Pf */
            b_pf: number;
            /** B Wins */
            b_wins: number;
            /** Ties */
            ties: number;
            /** Win Pct */
            win_pct: number;
        };
        /** RivalryTrend */
        RivalryTrend: {
            /** A Pf */
            a_pf: number;
            /** A Wins */
            a_wins: number;
            /** B Pf */
            b_pf: number;
            /** B Wins */
            b_wins: number;
            /** Year */
            year: number;
        };
        /** ScoreDistributionRow */
        ScoreDistributionRow: {
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Min */
            min: number;
            /** N */
            n: number;
            /** Outliers */
            outliers: number[];
            /** Q1 */
            q1: number;
            /** Q3 */
            q3: number;
            /** Std Dev */
            std_dev: number;
        };
        /** SeasonAwards */
        SeasonAwards: {
            /** Awards */
            awards: components["schemas"]["Award"][];
            /** Year */
            year: number | null;
        };
        /** SeasonDetail */
        SeasonDetail: {
            /** Id */
            id: number;
            /** League Name */
            league_name: string | null;
            /** Num Playoff Teams */
            num_playoff_teams: number | null;
            /** Num Regular Season Weeks */
            num_regular_season_weeks: number | null;
            /** Num Teams */
            num_teams: number | null;
            /** Standings */
            standings: components["schemas"]["StandingsRow"][];
            /** Year */
            year: number;
        };
        /** SeasonScoringData */
        SeasonScoringData: {
            /** Managers */
            managers: string[];
            /** Seasons */
            seasons: {
                [key: string]: number | null;
            }[];
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Champion Name */
            champion_name: string | null;
            /** Id */
            id: number;
            /** League Name */
            league_name: string | null;
            /** Num Teams */
            num_teams: number | null;
            /** Year */
            year: number;
        };
        /** StandingsRow */
        StandingsRow: {
            /** Final Rank */
            final_rank: number | null;
            /** Is Champion */
            is_champion: boolean;
            /** Losses */
            losses: number;
            /** Made Playoffs */
            made_playoffs: boolean;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Playoff Finish */
            playoff_finish: number | null;
            /** Points Against */
            points_against: number;
            /** Points For */
            points_for: number;
            /** Team Name */
            team_name: string | null;
            /** Ties */
            ties: number;
            /** Wins */
            wins: number;
        };
        /** StreakRow */
        StreakRow: {
            /** Current Streak Length */
            current_streak_length: number;
            /** Current Streak Type */
            current_streak_type: string;
            /** Longest Loss End Week */
            longest_loss_end_week: number | null;
            /** Longest Loss End Year */
            longest_loss_end_year: number | null;
            /** Longest Loss Start Week */
            longest_loss_start_week: number | null;
            /** Longest Loss Start Year */
            longest_loss_start_year: number | null;
            /** Longest Loss Streak */
            longest_loss_streak: number;
            /** Longest Win End Week */
            longest_win_end_week: number | null;
            /** Longest Win End Year */
            longest_win_end_year: number | null;
            /** Longest Win Start Week */
            longest_win_start_week: number | null;
            /** Longest Win Start Year */
            longest_win_start_year: number | null;
            /** Longest Win Streak */
            longest_win_streak: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
        };
        /** StrengthOfScheduleRow */
        StrengthOfScheduleRow: {
            /** Actual Win Pct */
            actual_win_pct: number;
            /** Adjusted Win Pct */
            adjusted_win_pct: number;
            /** Avg Opp Pf */
            avg_opp_pf: number;
            /** Avg Opp Win Pct */
            avg_opp_win_pct: number;
            /** Games */
            games: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Sos Rank */
            sos_rank: number;
            /** Wins Above Expected */
            wins_above_expected: number;
            /** Year */
            year: number | null;
        };
        /** SyncLogResponse */
        SyncLogResponse: {
            /** Error Msg */
            error_msg: string | null;
            /** Id */
            id: number;
            /** Season Year */
            season_year: number;
            /** Status */
            status: string;
            /** Synced At */
            synced_at: string | null;
            /** Week */
            week: number | null;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Error Msg */
            error_msg: string | null;
            /** Season Year */
            season_year: number;
            /** Status */
            status: string;
            /** Synced At */
            synced_at: string | null;
        };
        /** ThroneEntry */
        ThroneEntry: {
            /** Champion Id */
            champion_id: number | null;
            /** Champion Name */
            champion_name: string | null;
            /** Year */
            year: number;
        };
        /** ThroneTracker */
        ThroneTracker: {
            /** Active Champion */
            active_champion: string | null;
            /** Dynasties */
            dynasties: components["schemas"]["Dynasty"][];
            most_titles: components["schemas"]["TitleCount"];
            /** Timeline */
            timeline: components["schemas"]["ThroneEntry"][];
        };
        /** TitleCount */
        TitleCount: {
            /** Count */
            count: number;
            /** Manager Name */
            manager_name: string | null;
        };
        /** TrophyCase */
        TrophyCase: {
            /** Best Regular Season */
            best_regular_season: number | null;
            /** Championships */
            championships: number[];
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Playoff Appearances */
            playoff_appearances: number[];
            /** Runner Ups */
            runner_ups: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyFinishRow */
        WeeklyFinishRow: {
            /** Bottom Half */
            bottom_half: number;
            /** Bottom Three */
            bottom_three: number;
            /** First */
            first: number;
            /** Last */
            last: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Pct Bottom Three */
            pct_bottom_three: number;
            /** Pct First */
            pct_first: number;
            /** Pct Last */
            pct_last: number;
            /** Pct Top Half */
            pct_top_half: number;
            /** Pct Top Three */
            pct_top_three: number;
            /** Top Half */
            top_half: number;
            /** Top Three */
            top_three: number;
            /** Total Weeks */
            total_weeks: number;
        };
        /** WeeklyRecordEntry */
        WeeklyRecordEntry: {
            /** League Id */
            league_id?: string | null;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
            /** Margin */
            margin?: number | null;
            /** Opponent Manager Name */
            opponent_manager_name: string | null;
            /** Opponent Points */
            opponent_points: number | null;
            /** Opponent Yahoo Team Id */
            opponent_yahoo_team_id?: number | null;
            /** Points */
            points: number;
            /** Team Name */
            team_name: string | null;
            /** Week */
            week: number;
            /** Yahoo Team Id */
            yahoo_team_id?: number | null;
            /** Year */
            year: number;
        };
        /** WeeklyRecords */
        WeeklyRecords: {
            /** Biggest Blowout */
            biggest_blowout: components["schemas"]["WeeklyRecordEntry"][];
            /** Closest Games */
            closest_games: components["schemas"]["WeeklyRecordEntry"][];
            /** Highest Losing Score */
            highest_losing_score: components["schemas"]["WeeklyRecordEntry"][];
            /** Highest Score */
            highest_score: components["schemas"]["WeeklyRecordEntry"][];
            /** Lowest Score */
            lowest_score: components["schemas"]["WeeklyRecordEntry"][];
            /** Lowest Winning Score */
            lowest_winning_score: components["schemas"]["WeeklyRecordEntry"][];
        };
        /** WinMarginRow */
        WinMarginRow: {
            /** Avg Loss Margin */
            avg_loss_margin: number;
            /** Avg Win Margin */
            avg_win_margin: number;
            /** Biggest Loss */
            biggest_loss: number;
            /** Biggest Win */
            biggest_win: number;
            /** Blowout Losses */
            blowout_losses: number;
            /** Blowout Wins */
            blowout_wins: number;
            /** Close Losses */
            close_losses: number;
            /** Close Wins */
            close_wins: number;
            /** Manager Id */
            manager_id: number;
            /** Manager Name */
            manager_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    draft_analysis_api_draft_analysis_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_feedback_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    keeper_board_api_keepers_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeeperBoard"];
                };
            };
        };
    };
    list_managers_api_managers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerStats"][];
                };
            };
        };
    };
    get_manager_api_managers__manager_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manager_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manager_streak_api_managers__manager_id__streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manager_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerStreak"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"][];
                };
            };
        };
    };
    get_season_api_seasons__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_matchups_api_seasons__year__matchups_get: {
        parameters: {
            query?: {
                week?: number | null;
            };
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_time_stats_api_stats_alltime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerStats"][];
                };
            };
        };
    };
    awards_api_stats_awards_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonAwards"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consistency_api_stats_consistency_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consolation_bracket_api_stats_consolation_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsolationRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    droughts_api_stats_droughts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DroughtRow"][];
                };
            };
        };
    };
    head_to_head_api_stats_headtohead_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2HMatrix"];
                };
            };
        };
    };
    insight_rankings_api_stats_insight_rankings__insight_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightRankings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    league_parity_api_stats_league_parity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueParityRow"][];
                };
            };
        };
    };
    luck_index_api_stats_luck_index_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LuckIndexRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manager_placements_api_stats_manager_placements_get: {
        parameters: {
            query?: {
                year_start?: number | null;
                year_end?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerPlacementRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manager_tiers_api_stats_manager_tiers_get: {
        parameters: {
            query?: {
                year_start?: number | null;
                year_end?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerTierRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playoff_performance_api_stats_playoff_performance_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayoffPerformanceRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    points_inflation_api_stats_points_inflation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InflationPoint"][];
                };
            };
        };
    };
    power_rankings_api_stats_power_rankings_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PowerRankingRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_performance_api_stats_projection_performance_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rivalry_api_stats_rivalry_get: {
        parameters: {
            query: {
                manager_a: number;
                manager_b: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RivalryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_distribution_api_stats_score_distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreDistributionRow"][];
                };
            };
        };
    };
    season_scoring_api_stats_season_scoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonScoringData"];
                };
            };
        };
    };
    streaks_api_stats_streaks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakRow"][];
                };
            };
        };
    };
    strength_of_schedule_api_stats_strength_of_schedule_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrengthOfScheduleRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    throne_tracker_api_stats_throne_tracker_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroneTracker"];
                };
            };
        };
    };
    trophy_case_api_stats_trophy_case__manager_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manager_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrophyCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_finish_distribution_api_stats_weekly_finish_distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyFinishRow"][];
                };
            };
        };
    };
    weekly_records_api_stats_weekly_records_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyRecords"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    win_margins_api_stats_win_margins_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WinMarginRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_log_api_sync_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncLogResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"][];
                };
            };
        };
    };
}
